/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/04NsQr3amU5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Blog() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <section className="bg-primary py-20 px-4 md:px-6 pt-40">
        <div className="container mx-auto max-w-4xl text-center text-primary-foreground">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">
            Discover the Latest Insights
          </h1>
          <p className="mt-4 text-lg">
            Explore our collection of thought-provoking articles and stay ahead
            of the curve.
          </p>
          <Link
            href="#"
            className="mt-8 inline-flex items-center rounded-md bg-primary-foreground px-4 py-2 text-sm font-medium text-primary hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            Read More
            <ArrowRightIcon className="ml-2 h-4 w-4" />
          </Link>
        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {[...Array(6)].map((_, index) => (
              <div key={index} className="rounded-lg bg-background shadow-md">
                <img
                  src="/placeholder.svg"
                  alt="Blog Post"
                  width={400}
                  height={225}
                  className="h-48 w-full rounded-t-lg object-cover"
                  style={{ aspectRatio: "400/225", objectFit: "cover" }}
                />
                <div className="p-4">
                  <h3 className="text-xl font-bold">Blog Post Title</h3>
                  <p className="mt-2 text-muted-foreground">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                    euismod, nisl eget ultricies tincidunt, nisl nisl aliquam
                    nisl, eget aliquam nisl nisl eget nisl.
                  </p>
                  <Link
                    href="#"
                    className="mt-4 inline-flex items-center font-medium text-primary hover:underline"
                    prefetch={false}
                  >
                    Read More
                    <ArrowRightIcon className="ml-2 h-4 w-4" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  );
}

function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
