/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/S772414H5lR
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Judson } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

judson({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
} from "@/components/ui/carousel";
import { Card } from "@/components/ui/card";
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
} from "@/components/ui/collapsible";

export function HomePage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Connecting Businesses and Freelancers
                </h1>
                <p className="max-w-[600px] text-muted-foreground md:text-xl">
                  Our platform helps companies find the best freelance talent
                  and empowers freelancers to showcase their skills and find
                  meaningful work.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Become a Freelancer
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Hire Freelancers
                </Link>
              </div>
            </div>
            <img
              src="/placeholder.svg"
              alt="Hero"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
              width="550"
              height="550"
            />
          </div>
        </div>
      </section>
      <section
        id="freelancer-form"
        className="w-full py-12 md:py-24 lg:py-32 bg-muted"
      >
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Become a Freelancer
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Join our network of talented freelancers and start finding
                meaningful work today.
              </p>
            </div>
            <form className="w-full max-w-md space-y-4">
              <Input type="text" placeholder="Name" className="w-full" />
              <Input type="email" placeholder="Email" className="w-full" />
              <Textarea
                placeholder="Skills and Availability"
                className="w-full"
              />
              <Button type="submit" className="w-full">
                Submit
              </Button>
            </form>
          </div>
        </div>
      </section>
      <section id="company-form" className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Hire Freelancers
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Post your project and let our network of talented freelancers
                apply.
              </p>
            </div>
            <form className="w-full max-w-md space-y-4">
              <Input
                type="text"
                placeholder="Company Name"
                className="w-full"
              />
              <Input
                type="email"
                placeholder="Contact Email"
                className="w-full"
              />
              <Textarea placeholder="Project Description" className="w-full" />
              <Button type="submit" className="w-full">
                Submit
              </Button>
            </form>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                FAQ
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Frequently Asked Questions
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Find answers to the most common questions about our company and
                services.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl gap-6 py-12 lg:grid-cols-2 lg:gap-12">
            {/* FAQ Items */}
            <CollapsibleItem question="What is Acme Inc?">
              Acme Inc is a leading provider of innovative software solutions.
              We specialize in developing cutting-edge technologies that help
              our clients streamline their operations and achieve their business
              goals.
            </CollapsibleItem>
            <CollapsibleItem question="What services do you offer?">
              Our services include custom software development, cloud-based
              solutions, data analytics, and IT consulting. We work closely with
              our clients to understand their unique needs and deliver tailored
              solutions that drive their success.
            </CollapsibleItem>
            <CollapsibleItem question="How can I get in touch with Acme Inc?">
              You can reach us by email at info@acmeinc.com or by phone at (123)
              456-7890. Our office is located at 123 Main Street, Anytown USA.
              We're available during regular business hours to assist you with
              any questions or concerns.
            </CollapsibleItem>
            <CollapsibleItem question="What is your company's mission?">
              Our mission is to empower our clients with innovative technology
              solutions that drive their success. We are committed to delivering
              exceptional service, fostering collaboration, and continuously
              improving our offerings to meet the evolving needs of our
              customers.
            </CollapsibleItem>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 border-t">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                What Our Clients Say
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Hear from the companies and freelancers who have found success
                using our platform.
              </p>
            </div>
            <Carousel className="w-full max-w-4xl">
              <CarouselContent>
                <CarouselItem>
                  <Card className="p-6 text-center">
                    <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                      &ldquo;Working with this platform has been a game-changer
                      for our business. We've found the perfect freelancers to
                      help us scale our operations.&rdquo;
                    </blockquote>
                    <div className="mt-4 flex items-center justify-center gap-2">
                      <img
                        src="/placeholder.svg"
                        width="80"
                        height="80"
                        alt="Company Logo"
                        className="h-10 w-10 rounded-full object-cover"
                        style={{ aspectRatio: "80/80", objectFit: "cover" }}
                      />
                      <div>
                        <div className="font-semibold">Acme Inc</div>
                        <div className="text-sm text-muted-foreground">
                          CEO, Jane Doe
                        </div>
                      </div>
                    </div>
                  </Card>
                </CarouselItem>
                <CarouselItem>
                  <Card className="p-6 text-center">
                    <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                      &ldquo;As a freelancer, this platform has been a
                      game-changer. I've been able to connect with amazing
                      clients and take on projects that align with my
                      skills.&rdquo;
                    </blockquote>
                    <div className="mt-4 flex items-center justify-center gap-2">
                      <img
                        src="/placeholder.svg"
                        width="80"
                        height="80"
                        alt="Freelancer Avatar"
                        className="h-10 w-10 rounded-full object-cover"
                        style={{ aspectRatio: "80/80", objectFit: "cover" }}
                      />
                      <div>
                        <div className="font-semibold">John Doe</div>
                        <div className="text-sm text-muted-foreground">
                          Freelance Designer
                        </div>
                      </div>
                    </div>
                  </Card>
                </CarouselItem>
                <CarouselItem>
                  <Card className="p-6 text-center">
                    <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                      &ldquo;This platform has been a game-changer for our
                      company. We've been able to find the perfect freelancers
                      to help us with our projects, and the process has been
                      seamless.&rdquo;
                    </blockquote>
                    <div className="mt-4 flex items-center justify-center gap-2">
                      <img
                        src="/placeholder.svg"
                        width="80"
                        height="80"
                        alt="Company Logo"
                        className="h-10 w-10 rounded-full object-cover"
                        style={{ aspectRatio: "80/80", objectFit: "cover" }}
                      />
                      <div>
                        <div className="font-semibold">Globex Corporation</div>
                        <div className="text-sm text-muted-foreground">
                          CEO, John Smith
                        </div>
                      </div>
                    </div>
                  </Card>
                </CarouselItem>
              </CarouselContent>
              <CarouselPrevious />
              <CarouselNext />
            </Carousel>
          </div>
        </div>
      </section>
    </div>
  );
}

function CollapsibleItem({ question, children }) {
  return (
    <Collapsible className="space-y-2">
      <CollapsibleTrigger className="flex items-center justify-between rounded-md bg-background px-4 py-3 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[state=open]:bg-accent/50">
        <span>{question}</span>
        <ChevronDownIcon className="h-5 w-5 transition-transform data-[state=open]:rotate-180" />
      </CollapsibleTrigger>
      <CollapsibleContent className="px-4 pb-4 text-muted-foreground">
        {children}
      </CollapsibleContent>
    </Collapsible>
  );
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}
