/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LbEFbVrbtJm
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
} from "@/components/ui/carousel";
import { Card, CardContent } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";

export function Services() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                    Our Services
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Acme Inc offers a wide range of services to help your
                    business succeed in the digital age.
                  </p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex flex-col items-start gap-1">
                    <BriefcaseIcon className="h-6 w-6 text-primary" />
                    <h3 className="text-lg font-semibold">Web Development</h3>
                    <p className="text-muted-foreground">
                      Our team of expert developers create custom web
                      applications and websites tailored to your business needs.
                      From e-commerce platforms to complex web applications, we
                      have the skills and experience to bring your digital
                      vision to life.
                    </p>
                  </div>
                  <div className="flex flex-col items-start gap-1">
                    <PaletteIcon className="h-6 w-6 text-primary" />
                    <h3 className="text-lg font-semibold">UI/UX Design</h3>
                    <p className="text-muted-foreground">
                      Our UI/UX designers craft intuitive and visually appealing
                      user experiences that engage your customers and drive
                      conversions. We use the latest design principles and user
                      research to ensure your digital products are both
                      beautiful and functional.
                    </p>
                  </div>
                  <div className="flex flex-col items-start gap-1">
                    <BarChartIcon className="h-6 w-6 text-primary" />
                    <h3 className="text-lg font-semibold">Analytics</h3>
                    <p className="text-muted-foreground">
                      Our analytics services provide you with the insights you
                      need to make data-driven decisions and drive your business
                      forward. We'll help you track key metrics, identify
                      trends, and uncover opportunities for growth.
                    </p>
                  </div>
                  <div className="flex flex-col items-start gap-1">
                    <ShieldIcon className="h-6 w-6 text-primary" />
                    <h3 className="text-lg font-semibold">Security</h3>
                    <p className="text-muted-foreground">
                      Protecting your business and your customers' data is our
                      top priority. We offer comprehensive security solutions to
                      safeguard your digital assets and ensure compliance with
                      industry regulations.
                    </p>
                  </div>
                  <div className="flex flex-col items-start gap-1">
                    <CloudIcon className="h-6 w-6 text-primary" />
                    <h3 className="text-lg font-semibold">Cloud Services</h3>
                    <p className="text-muted-foreground">
                      Our cloud infrastructure services provide you with
                      scalable, reliable, and cost-effective solutions to power
                      your digital applications. We'll help you leverage the
                      power of the cloud to drive innovation and growth.
                    </p>
                  </div>
                  <div className="flex flex-col items-start gap-1">
                    <RocketIcon className="h-6 w-6 text-primary" />
                    <h3 className="text-lg font-semibold">Digital Marketing</h3>
                    <p className="text-muted-foreground">
                      Our digital marketing experts will help you reach new
                      customers and grow your online presence. From search
                      engine optimization to social media marketing, we'll
                      develop a comprehensive strategy to drive traffic and
                      conversions.
                    </p>
                  </div>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="500"
                height="400"
                alt="Our Services"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                    What Our Clients Say
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Hear from the businesses and freelancers who have partnered
                    with us.
                  </p>
                </div>
                <Carousel className="w-full max-w-lg">
                  <CarouselContent>
                    <CarouselItem>
                      <Card>
                        <CardContent className="space-y-4">
                          <blockquote className="text-lg font-semibold leading-snug">
                            &ldquo;Acme Inc has been an invaluable partner in
                            our business growth. Their team's expertise and
                            dedication have been instrumental in our
                            success.&rdquo;
                          </blockquote>
                          <div className="flex items-center gap-4">
                            <Avatar>
                              <AvatarImage src="/placeholder-user.jpg" />
                              <AvatarFallback>JD</AvatarFallback>
                            </Avatar>
                            <div>
                              <p className="text-sm font-medium">
                                Jane Doe, CEO
                              </p>
                              <p className="text-sm text-muted-foreground">
                                Acme Corp
                              </p>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    </CarouselItem>
                    <CarouselItem>
                      <Card>
                        <CardContent className="space-y-4">
                          <blockquote className="text-lg font-semibold leading-snug">
                            &ldquo;Working with Acme Inc has been a game-changer
                            for my freelance business. Their platform and
                            support have helped me connect with amazing clients
                            and grow my skills.&rdquo;
                          </blockquote>
                          <div className="flex items-center gap-4">
                            <Avatar>
                              <AvatarImage src="/placeholder-user.jpg" />
                              <AvatarFallback>JD</AvatarFallback>
                            </Avatar>
                            <div>
                              <p className="text-sm font-medium">
                                John Doe, Freelance Designer
                              </p>
                              <p className="text-sm text-muted-foreground">
                                Acme Designs
                              </p>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    </CarouselItem>
                  </CarouselContent>
                  <CarouselPrevious />
                  <CarouselNext />
                </Carousel>
              </div>
              <div className="space-y-4">
                <img
                  src="/placeholder.svg"
                  width="500"
                  height="400"
                  alt="Testimonials"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  );
}

function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  );
}

function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}

function PaletteIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />
      <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z" />
    </svg>
  );
}

function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  );
}

function ShieldIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
    </svg>
  );
}
